services:

  backend:
    build:
     context: ./backend
     target: production
    volumes:
     - ./backend:/app
    networks:
     - tipping-network
    ports:
     - 8000:8000

networks:
  tipping-network: {}
