[build-system]
requires = ["setuptools==82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "django-tipping"
version = "0.0.0"
description = "Simple Django Application for managing and conducting sports tipping competitions."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Blake McIvor" },
]
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Software Development",
]
keywords = ["django-tipping", "tipping"]
dependencies = [
    "django==6.0.7",
    "psycopg2-binary==2.9.12",
]

[project.urls]
Homepage = "https://github.com/bmcivor/django-tipping"
Repository = "https://github.com/bmcivor/django-tipping"
Issues = "https://github.com/bmcivor/django-tipping/issues"

[project.scripts]

[dependency-groups]
dev = [
    "pytest==9.0.2",
    "python-semantic-release==9.21.1",
]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
tag_format = "v{version}"
build_command = "uv lock --no-cache --no-progress"
assets = ["uv.lock"]

[tool.semantic_release.branches.main]
match = "tag-release"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["tests"]
