# Generated by Django 6.0.7 on 2026-08-10 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "matches"},
        ),
    ]
